#!/usr/bin/env python3
"""
Setup Wizard for idIAmas
Helps users configure the application without manual environment variable editing
"""

import os
import sys
import json
from pathlib import Path

def create_env_file():
    """Create .env file with user input"""
    print("🎯 idIAmas Setup Wizard")
    print("=" * 50)
    
    # Check if .env already exists
    env_path = Path(".env")
    if env_path.exists():
        overwrite = input("⚠️  .env file already exists. Overwrite? (y/N): ").lower()
        if overwrite != 'y':
            print("Setup cancelled.")
            return False
    
    print("\n📝 Let's configure your idIAmas application!")
    print("\n1️⃣  OpenAI API Key (Required)")
    print("   Get your key from: https://platform.openai.com/api-keys")
    
    api_key = ""
    while not api_key:
        api_key = input("   Enter your OpenAI API key: ").strip()
        if not api_key.startswith("sk-"):
            print("   ❌ API key should start with 'sk-'. Please try again.")
            api_key = ""
    
    print("\n2️⃣  Screen Region (Optional - press Enter for defaults)")
    print("   This defines where subtitles appear on your screen")
    print("   Format: x,y,width,height (e.g., 150,750,1520,330)")
    
    region = input("   Screen region (default: 150,750,1520,330): ").strip()
    if not region:
        region = "150,750,1520,330"
    
    print("\n3️⃣  Language (Optional - press Enter for Italian)")
    language = input("   OCR language (default: ita): ").strip()
    if not language:
        language = "ita"
    
    # Create .env content
    env_content = f"""# idIAmas Configuration
# Generated by setup wizard

# OpenAI Configuration
OPENAI_API_KEY={api_key}

# Screen Region for Subtitles (x, y, width, height)
SUBTITLES_REGION={region}

# OpenAI Model Settings
OPENAI_MODEL=gpt-3.5-turbo
MAX_TOKENS=500
TEMPERATURE=0.7

# OCR Settings
OCR_LANGUAGE={language}
IMAGE_THRESHOLD=200

# Note: This file contains sensitive information
# Never commit it to version control
"""
    
    # Write .env file
    try:
        with open(env_path, 'w', encoding='utf-8') as f:
            f.write(env_content)
        
        print(f"\n✅ Configuration saved to {env_path}")
        print("🔒 This file is automatically ignored by git for security")
        
        return True
        
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")
        return False

def create_config_guide():
    """Create a configuration guide for users"""
    guide_content = """# 🎯 idIAmas Configuration Guide

## Quick Setup Options

### Option 1: Use the Setup Wizard (Recommended)
```bash
python setup.py
```

### Option 2: Manual Configuration
1. Copy `config.example.txt` to `.env`
2. Edit `.env` and add your OpenAI API key
3. Adjust other settings as needed

### Option 3: System Environment Variables
Set these in your system:
- `OPENAI_API_KEY` - Your OpenAI API key
- `SUBTITLES_REGION` - Screen coordinates (optional)

## Getting Your OpenAI API Key

1. Visit [https://platform.openai.com/api-keys](https://platform.openai.com/api-keys)
2. Sign in to your OpenAI account
3. Click "Create new secret key"
4. Copy the key (starts with `sk-`)
5. Paste it in your configuration

## Testing Your Setup

Run this to test if everything is configured:
```bash
python -c "import os; print('✅ Ready!' if os.getenv('OPENAI_API_KEY') else '❌ Missing API key')"
```

## Need Help?

- Check the README.md for detailed instructions
- Review the error messages in the application
- Ensure Tesseract OCR is installed for text extraction
"""
    
    try:
        with open("CONFIGURATION.md", 'w', encoding='utf-8') as f:
            f.write(guide_content)
        print("📖 Configuration guide created: CONFIGURATION.md")
    except Exception as e:
        print(f"⚠️  Could not create configuration guide: {e}")

def main():
    """Main setup function"""
    print("🚀 Welcome to idIAmas Setup!")
    
    # Check if running in the right directory
    if not Path("main.py").exists():
        print("❌ Error: Please run this script from the idIAmas project directory")
        sys.exit(1)
    
    # Create configuration guide
    create_config_guide()
    
    # Run setup wizard
    if create_env_file():
        print("\n🎉 Setup complete! You can now run:")
        print("   python main.py")
        print("\n📚 Check CONFIGURATION.md for more details")
    else:
        print("\n❌ Setup failed. Please check the error messages above.")
        sys.exit(1)

if __name__ == "__main__":
    main()
